export interface BNEMaterial{
  id: string,
  title: string,
  author: string,
  organisation: string,
  type: string,
  licence: string,
  topic: string,
  keywords: string,
  ageRecommend: string,
  subject: string,
  level: string,
  description: string,
  evaluation: string,
  url: string,
  fileAttachmentUrl: string,
  licenceUrl: string,
  evaluationConceptIds: string[],
  evaluationConcept: number[],
  evaluationTestedIds: string[],
  evaluationTested: number[],
  foundByName: string,
  foundById: string,
  examinedById: string,
  examinedByName: string,
  examinationState: number,
  proofExaminedUrl: string,
  externExamination: boolean,
  externExaminationEMail: string,
  externExaminationName:string,
  SDGGoals: string,
  commentCount: number
}
